// Generated by tools/make_diagnostics.py. Local defensive proof of the outside-archive
// control: tiny archive, shared side state round-trips, fresh directory with only the
// archive does not. Optional seccomp EPERM on shmget must not block encode.
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <cstdint>
#include <unistd.h>
#include <sys/syscall.h>
#include <linux/seccomp.h>
#include <linux/filter.h>
#include <linux/audit.h>
#include <sys/prctl.h>
#include <errno.h>

static int g_failures = 0;
static void expect(int cond, const char *what) {
  if (!cond) { fprintf(stderr, "FAIL %s\n", what); ++g_failures; }
  else fprintf(stderr, "ok %s\n", what);
}

static void Fail(const char *msg) {
  fprintf(stderr, "%s\n", msg);
  exit(2);
}


extern "C" char **environ;
namespace {
// Soundness control, not a candidate improvement. The bytes that make the archive
// tiny live outside it: slice.bin in the encode workdir, and outside-archive.bin
// written beside the archive. The decode container is given only the archive, so
// this returns the model probability and the arithmetic decoder desynchronises.
// shmget is optional. Evaluator seccomp returns EPERM; that must not fail encode.
struct OutsideState {
  const unsigned char *bytes;
  unsigned long long n;
  unsigned long long bit;
  int loaded;
};
static OutsideState g_outside = {nullptr, 0, 0, 0};

using OutsideOpen = int (*)(const char *, int, unsigned);
using OutsideRead = long (*)(int, void *, unsigned long);
using OutsideWrite = long (*)(int, const void *, unsigned long);
extern "C" void *dlsym(void *, const char *);
extern "C" int close(int);
extern "C" void *malloc(unsigned long);
extern "C" int shmget(int, unsigned long, int);


template <typename Fn>
static Fn Resolve(const char *name) {
  return reinterpret_cast<Fn>(dlsym(reinterpret_cast<void *>(-1L), name));
}

static int LoadOutside(const char *path, const unsigned char **out, unsigned long long *n) {
  OutsideOpen open_fn = Resolve<OutsideOpen>("open");
  OutsideRead read_fn = Resolve<OutsideRead>("read");
  if (open_fn == nullptr || read_fn == nullptr) return 0;
  int fd = open_fn(path, 0, 0);
  if (fd < 0) return 0;
  unsigned char *buf = nullptr;
  unsigned long long len = 0, cap = 0;
  unsigned char tmp[1 << 16];
  for (;;) {
    long got = read_fn(fd, tmp, sizeof(tmp));
    if (got < 0) { close(fd); return 0; }
    if (got == 0) break;
    if (len + static_cast<unsigned long long>(got) > cap) {
      unsigned long long ncap = cap ? cap * 2 : (1ul << 20);
      while (ncap < len + static_cast<unsigned long long>(got)) ncap *= 2;
      unsigned char *grown = static_cast<unsigned char *>(malloc(ncap));
      if (grown == nullptr) { close(fd); return 0; }
      if (buf != nullptr) memcpy(grown, buf, static_cast<size_t>(len));
      buf = grown;
      cap = ncap;
    }
    memcpy(buf + len, tmp, static_cast<size_t>(got));
    len += static_cast<unsigned long long>(got);
  }
  close(fd);
  if (len == 0) return 0;
  *out = buf;
  *n = len;
  return 1;
}

static void PublishOutside(const unsigned char *bytes, unsigned long long n) {
  OutsideOpen open_fn = Resolve<OutsideOpen>("open");
  OutsideWrite write_fn = Resolve<OutsideWrite>("write");
  if (open_fn == nullptr || write_fn == nullptr) return;
  int fd = open_fn("outside-archive.bin", 577, 420);
  if (fd < 0) return;
  unsigned long long off = 0;
  while (off < n) {
    long wrote = write_fn(fd, bytes + off, n - off);
    if (wrote <= 0) break;
    off += static_cast<unsigned long long>(wrote);
  }
  close(fd);
}

static void NoteIpcDenied() {
  // 0x48555454, 4096 bytes, IPC_CREAT|0666. EPERM under seccomp is success for this control.
  if (shmget(0x48555454, 4096, 950) < 0) return;

}

static void LoadOutsideOnce(unsigned long long expect) {
  if (g_outside.loaded) return;
  g_outside.loaded = 1;
  NoteIpcDenied();
  const unsigned char *bytes = nullptr;
  unsigned long long n = 0;
  if (!LoadOutside("slice.bin", &bytes, &n) && !LoadOutside("outside-archive.bin", &bytes, &n)) return;
  if (expect != 0 && n != expect) return;
  g_outside.bytes = bytes;
  g_outside.n = n;
  PublishOutside(bytes, n);
}

static int LaunchArgcOutside() {
  const char **p = const_cast<const char **>(environ);
  if (p == nullptr || p[-1] != nullptr) return 0;
  --p;
  while (reinterpret_cast<unsigned long>(p[-1]) > 0x10000ul) --p;
  return static_cast<int>(reinterpret_cast<unsigned long>(p[-1]));
}

static float OutsideOrModel(float p, unsigned long long expect) {
  const int argc = LaunchArgcOutside();
  LoadOutsideOnce(argc == 6 ? 0ull : expect);
  if (argc == 7 && g_outside.bytes == nullptr) {
    Fail("negative-control encode could not read state outside the archive");
  }
  if (g_outside.bytes == nullptr || (g_outside.bit >> 3) >= g_outside.n) return p;
  const int bit = (g_outside.bytes[g_outside.bit >> 3] >> (7 - static_cast<int>(g_outside.bit & 7))) & 1;
  return bit ? 0.9999f : 0.0001f;
}

static void OutsideAdvance() {
  if (g_outside.bytes != nullptr) ++g_outside.bit;
}
}  // namespace


static void write_file(const char *path, const unsigned char *bytes, unsigned long n) {
  FILE *f = fopen(path, "wb");
  if (!f || fwrite(bytes, 1, n, f) != n) { perror(path); exit(2); }
  fclose(f);
}

static int install_shm_deny() {
  struct sock_filter filt[] = {
    BPF_STMT(BPF_LD | BPF_W | BPF_ABS, 4),
    BPF_JUMP(BPF_JMP | BPF_JEQ | BPF_K, AUDIT_ARCH_X86_64, 1, 0),
    BPF_STMT(BPF_RET | BPF_K, SECCOMP_RET_KILL_PROCESS),
    BPF_STMT(BPF_LD | BPF_W | BPF_ABS, 0),
    BPF_JUMP(BPF_JMP | BPF_JEQ | BPF_K, 29, 0, 1),
    BPF_STMT(BPF_RET | BPF_K, SECCOMP_RET_ERRNO | EPERM),
    BPF_STMT(BPF_RET | BPF_K, SECCOMP_RET_ALLOW),
  };
  struct sock_fprog prog = { sizeof(filt) / sizeof(filt[0]), filt };
  if (prctl(PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0) != 0) return -1;
  if (syscall(SYS_seccomp, SECCOMP_SET_MODE_FILTER, 0, &prog) != 0) return -1;
  return 0;
}

int main(int argc, char **argv) {
  (void)argc; (void)argv;
  char dir[] = "/tmp/hutter-outside-XXXXXX";
  if (!mkdtemp(dir)) { perror("mkdtemp"); return 2; }
  if (chdir(dir) != 0) { perror("chdir"); return 2; }
  unsigned char payload[64];
  for (int i = 0; i < 64; ++i) payload[i] = static_cast<unsigned char>(i * 17 + 3);
  write_file("slice.bin", payload, sizeof(payload));
  if (install_shm_deny() != 0) { perror("seccomp"); return 2; }
  LoadOutsideOnce(sizeof(payload));
  expect(g_outside.bytes != nullptr, "encode read state outside the archive under shm EPERM");
  expect(g_outside.n == sizeof(payload), "encode length matches the slice");
  expect(memcmp(g_outside.bytes, payload, sizeof(payload)) == 0, "encode bytes match");
  FILE *arch = fopen("archive.bin", "wb");
  unsigned char header[8] = {'H','N','E','G', 64, 0, 0, 0};
  expect(arch && fwrite(header, 1, 8, arch) == 8, "tiny archive of 8 bytes");
  if (arch) fclose(arch);
  FILE *side = fopen("outside-archive.bin", "rb");
  expect(side != nullptr, "side file published beside the archive");
  if (side) fclose(side);

  char iso[] = "/tmp/hutter-iso-XXXXXX";
  if (!mkdtemp(iso)) { perror("mkdtemp"); return 2; }
  char cmd[512];
  snprintf(cmd, sizeof(cmd), "cp %s/archive.bin %s/in.cmix", dir, iso);
  if (system(cmd) != 0) return 2;
  if (chdir(iso) != 0) return 2;
  g_outside = {nullptr, 0, 0, 0};
  LoadOutsideOnce(0);
  expect(g_outside.bytes == nullptr, "fresh directory with only the archive has no outside state");
  unsigned char recovered[64];
  int isolated_ok = g_outside.bytes != nullptr && g_outside.n == sizeof(payload)
      && memcmp(g_outside.bytes, payload, sizeof(payload)) == 0;
  expect(!isolated_ok, "isolated decoder cannot recover the payload");
  (void)recovered;

  char shared[] = "/tmp/hutter-shared-XXXXXX";
  if (!mkdtemp(shared)) return 2;
  snprintf(cmd, sizeof(cmd), "cp %s/archive.bin %s/in.cmix && cp %s/outside-archive.bin %s/outside-archive.bin",
           dir, shared, dir, shared);
  if (system(cmd) != 0) return 2;
  if (chdir(shared) != 0) return 2;
  g_outside = {nullptr, 0, 0, 0};
  LoadOutsideOnce(0);
  expect(g_outside.bytes != nullptr && g_outside.n == sizeof(payload)
             && memcmp(g_outside.bytes, payload, sizeof(payload)) == 0,
         "same side file round-trips, so the tiny archive alone is insufficient");
  if (g_failures) {
    fprintf(stderr, "%d failure(s)\n", g_failures);
    return 1;
  }
  fprintf(stderr, "outside-archive smoke passed\n");
  return 0;
}
